<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TaskTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing templates first to prevent duplication
        DB::table('task_templates')->truncate();

        $templates = [
            // SEO project type
            [
                'project_type' => 'seo',
                'title' => 'Initial SEO Audit',
                'description' => 'Technical audit of site structure, performance, indexation, and errors.',
                'type' => 'seo_audit',
                'role_required' => 'analyst',
                'estimated_hours' => 8.00,
                'sla_hours' => 48,
                'sort_order' => 1,
                'depends_on' => null,
            ],
            [
                'project_type' => 'seo',
                'title' => 'Keyword Research',
                'description' => 'Competitor + volume analysis to identify high-value search terms.',
                'type' => 'research',
                'role_required' => 'analyst',
                'estimated_hours' => 6.00,
                'sla_hours' => 72,
                'sort_order' => 2,
                'depends_on' => null,
            ],
            [
                'project_type' => 'seo',
                'title' => 'On-Page Optimisation Plan',
                'description' => 'Create strategic implementation plan based on audit and keyword research.',
                'type' => 'research',
                'role_required' => 'analyst',
                'estimated_hours' => 4.00,
                'sla_hours' => 48,
                'sort_order' => 3,
                'depends_on' => [1, 2],
            ],
            [
                'project_type' => 'seo',
                'title' => 'Content Brief Creation',
                'description' => 'Draft detailed content briefs targeting optimized keyword clusters.',
                'type' => 'content',
                'role_required' => 'marketer',
                'estimated_hours' => 3.00,
                'sla_hours' => 48,
                'sort_order' => 4,
                'depends_on' => [3],
            ],
            [
                'project_type' => 'seo',
                'title' => 'Content Writing',
                'description' => 'Author optimized articles, pages, or blogs according to content briefs.',
                'type' => 'content',
                'role_required' => 'copywriter',
                'estimated_hours' => 8.00,
                'sla_hours' => 120,
                'sort_order' => 5,
                'depends_on' => [4],
            ],
            [
                'project_type' => 'seo',
                'title' => 'Technical Fixes Implementation',
                'description' => 'Deploy technical recommendations (speed improvements, schema markup, redirects).',
                'type' => 'other',
                'role_required' => 'developer',
                'estimated_hours' => 6.00,
                'sla_hours' => 96,
                'sort_order' => 6,
                'depends_on' => [3],
            ],
            [
                'project_type' => 'seo',
                'title' => 'Backlink Outreach Setup',
                'description' => 'Establish campaign targets and pitch scripts for contextually relevant link building.',
                'type' => 'other',
                'role_required' => 'marketer',
                'estimated_hours' => 4.00,
                'sla_hours' => 72,
                'sort_order' => 7,
                'depends_on' => [3],
            ],
            [
                'project_type' => 'seo',
                'title' => 'Monthly Report Setup',
                'description' => 'Map analytics tracking dashboard and configure initial snapshot targets.',
                'type' => 'report',
                'role_required' => 'analyst',
                'estimated_hours' => 2.00,
                'sla_hours' => 24,
                'sort_order' => 8,
                'depends_on' => [1],
            ],
            [
                'project_type' => 'seo',
                'title' => 'Client Kickoff Meeting',
                'description' => 'Review project timeline, strategy, deliverables, and communication protocols.',
                'type' => 'meeting',
                'role_required' => 'project_manager',
                'estimated_hours' => 1.00,
                'sla_hours' => 24,
                'sort_order' => 9,
                'depends_on' => null,
            ],

            // PERFORMANCE_ADS project type
            [
                'project_type' => 'performance_ads',
                'title' => 'Ad Account Audit',
                'description' => 'Examine active campaigns, history, pixel health, and historical CPI/ROAS.',
                'type' => 'other',
                'role_required' => 'analyst',
                'estimated_hours' => 4.00,
                'sla_hours' => 24,
                'sort_order' => 1,
                'depends_on' => null,
            ],
            [
                'project_type' => 'performance_ads',
                'title' => 'Audience Research',
                'description' => 'Define target demographics, interest clusters, and lookalike parameters.',
                'type' => 'research',
                'role_required' => 'analyst',
                'estimated_hours' => 4.00,
                'sla_hours' => 48,
                'sort_order' => 2,
                'depends_on' => null,
            ],
            [
                'project_type' => 'performance_ads',
                'title' => 'Campaign Strategy Document',
                'description' => 'Formulate ad budget allocation, bidding strategy, and conversion objectives.',
                'type' => 'other',
                'role_required' => 'project_manager',
                'estimated_hours' => 3.00,
                'sla_hours' => 48,
                'sort_order' => 3,
                'depends_on' => [1, 2],
            ],
            [
                'project_type' => 'performance_ads',
                'title' => 'Ad Creative Brief',
                'description' => 'Outline creative direction, hooks, body copy options, and visual layouts.',
                'type' => 'content',
                'role_required' => 'marketer',
                'estimated_hours' => 2.00,
                'sla_hours' => 48,
                'sort_order' => 4,
                'depends_on' => [3],
            ],
            [
                'project_type' => 'performance_ads',
                'title' => 'Creative Production',
                'description' => 'Design static banners, carousels, or edit short-form videos.',
                'type' => 'design',
                'role_required' => 'designer',
                'estimated_hours' => 8.00,
                'sla_hours' => 96,
                'sort_order' => 5,
                'depends_on' => [4],
            ],
            [
                'project_type' => 'performance_ads',
                'title' => 'Campaign Setup in Meta Ads',
                'description' => 'Construct campaigns, build ad sets, upload creative assets, and deploy tracking.',
                'type' => 'campaign_setup',
                'role_required' => 'marketer',
                'estimated_hours' => 4.00,
                'sla_hours' => 48,
                'sort_order' => 6,
                'depends_on' => [5],
            ],
            [
                'project_type' => 'performance_ads',
                'title' => 'Pixel/Tracking Verification',
                'description' => 'Test event firing using test conversions to ensure precision in tracking.',
                'type' => 'other',
                'role_required' => 'developer',
                'estimated_hours' => 2.00,
                'sla_hours' => 24,
                'sort_order' => 7,
                'depends_on' => [6],
            ],
            [
                'project_type' => 'performance_ads',
                'title' => 'Launch Review',
                'description' => 'Double check variables, limits, delivery, and schedule release.',
                'type' => 'review',
                'role_required' => 'project_manager',
                'estimated_hours' => 1.00,
                'sla_hours' => 12,
                'sort_order' => 8,
                'depends_on' => [6, 7],
            ],
            [
                'project_type' => 'performance_ads',
                'title' => 'Weekly Performance Report Template',
                'description' => 'Establish metric pull routines and prepare initial summary layout.',
                'type' => 'report',
                'role_required' => 'analyst',
                'estimated_hours' => 2.00,
                'sla_hours' => 24,
                'sort_order' => 9,
                'depends_on' => null,
            ],

            // WEB_DEV project type
            [
                'project_type' => 'web_dev',
                'title' => 'Requirements Gathering',
                'description' => 'Collate sitemaps, system features, custom flows, and design preferences.',
                'type' => 'research',
                'role_required' => 'project_manager',
                'estimated_hours' => 4.00,
                'sla_hours' => 24,
                'sort_order' => 1,
                'depends_on' => null,
            ],
            [
                'project_type' => 'web_dev',
                'title' => 'Wireframe Design',
                'description' => 'Sketch structural layout and user journeys for desktop/mobile viewports.',
                'type' => 'design',
                'role_required' => 'designer',
                'estimated_hours' => 8.00,
                'sla_hours' => 96,
                'sort_order' => 2,
                'depends_on' => [1],
            ],
            [
                'project_type' => 'web_dev',
                'title' => 'Design Approval',
                'description' => 'Review design iterations and sign off with client stakeholders.',
                'type' => 'review',
                'role_required' => 'project_manager',
                'estimated_hours' => 1.00,
                'sla_hours' => 24,
                'sort_order' => 3,
                'depends_on' => [2],
            ],
            [
                'project_type' => 'web_dev',
                'title' => 'Frontend Development',
                'description' => 'Slice designs into semantic HTML/CSS/JS and build responsive layouts.',
                'type' => 'feature',
                'role_required' => 'developer',
                'estimated_hours' => 40.00,
                'sla_hours' => 240,
                'sort_order' => 4,
                'depends_on' => [3],
            ],
            [
                'project_type' => 'web_dev',
                'title' => 'Backend Development',
                'description' => 'Structure database schemas, configure system logic, APIs, and Admin portals.',
                'type' => 'feature',
                'role_required' => 'developer',
                'estimated_hours' => 30.00,
                'sla_hours' => 240,
                'sort_order' => 5,
                'depends_on' => [3],
            ],
            [
                'project_type' => 'web_dev',
                'title' => 'Content Upload',
                'description' => 'Publish page copies, media assets, blog templates, and catalog structures.',
                'type' => 'content',
                'role_required' => 'marketer',
                'estimated_hours' => 8.00,
                'sla_hours' => 96,
                'sort_order' => 6,
                'depends_on' => [4],
            ],
            [
                'project_type' => 'web_dev',
                'title' => 'QA Testing',
                'description' => 'Run manual/automated tests covering responsiveness, speed, and functional logic.',
                'type' => 'bug',
                'role_required' => 'developer',
                'estimated_hours' => 8.00,
                'sla_hours' => 48,
                'sort_order' => 7,
                'depends_on' => [4, 5],
            ],
            [
                'project_type' => 'web_dev',
                'title' => 'Client UAT',
                'description' => 'Host walkthrough sessions and track comments, change logs, and bugs.',
                'type' => 'review',
                'role_required' => 'project_manager',
                'estimated_hours' => 4.00,
                'sla_hours' => 48,
                'sort_order' => 8,
                'depends_on' => [7],
            ],
            [
                'project_type' => 'web_dev',
                'title' => 'Go Live',
                'description' => 'Configure host name mappings, SSL certificates, cache engines, and launch site.',
                'type' => 'other',
                'role_required' => 'developer',
                'estimated_hours' => 2.00,
                'sla_hours' => 24,
                'sort_order' => 9,
                'depends_on' => [8],
            ],
            [
                'project_type' => 'web_dev',
                'title' => 'Post-Launch Monitoring',
                'description' => 'Audit server logs, search console indexing, analytics tracking, and script issues.',
                'type' => 'other',
                'role_required' => 'developer',
                'estimated_hours' => 2.00,
                'sla_hours' => 72,
                'sort_order' => 10,
                'depends_on' => [9],
            ],

            // SOCIAL_MEDIA project type
            [
                'project_type' => 'social_media',
                'title' => 'Brand Voice & Style Guide',
                'description' => 'Define tone of voice, visual direction, color palettes, and hashtag templates.',
                'type' => 'design',
                'role_required' => 'marketer',
                'estimated_hours' => 4.00,
                'sla_hours' => 48,
                'sort_order' => 1,
                'depends_on' => null,
            ],
            [
                'project_type' => 'social_media',
                'title' => 'Content Calendar — Month 1',
                'description' => 'Draft distribution outline mapping campaigns and post clusters.',
                'type' => 'content',
                'role_required' => 'marketer',
                'estimated_hours' => 4.00,
                'sla_hours' => 48,
                'sort_order' => 2,
                'depends_on' => [1],
            ],
            [
                'project_type' => 'social_media',
                'title' => 'Graphic Templates Creation',
                'description' => 'Produce master Canva or Illustrator layouts for posts, stories, and reels.',
                'type' => 'design',
                'role_required' => 'designer',
                'estimated_hours' => 8.00,
                'sla_hours' => 96,
                'sort_order' => 3,
                'depends_on' => [1],
            ],
            [
                'project_type' => 'social_media',
                'title' => 'Content Writing — Week 1',
                'description' => 'Write post copies, descriptions, and hashtags for initial week.',
                'type' => 'content',
                'role_required' => 'marketer',
                'estimated_hours' => 3.00,
                'sla_hours' => 48,
                'sort_order' => 4,
                'depends_on' => [2],
            ],
            [
                'project_type' => 'social_media',
                'title' => 'Design — Week 1 Posts',
                'description' => 'Apply copy outlines to graphic templates for publication release.',
                'type' => 'design',
                'role_required' => 'designer',
                'estimated_hours' => 4.00,
                'sla_hours' => 48,
                'sort_order' => 5,
                'depends_on' => [4],
            ],
            [
                'project_type' => 'social_media',
                'title' => 'Scheduling Setup',
                'description' => 'Queue finalized graphic assets and copies inside buffer or direct channels.',
                'type' => 'other',
                'role_required' => 'marketer',
                'estimated_hours' => 1.00,
                'sla_hours' => 24,
                'sort_order' => 6,
                'depends_on' => [5],
            ],
            [
                'project_type' => 'social_media',
                'title' => 'Monthly Analytics Report',
                'description' => 'Map engagement rates, reach trends, audience profile growth, and best times.',
                'type' => 'report',
                'role_required' => 'analyst',
                'estimated_hours' => 2.00,
                'sla_hours' => 24,
                'sort_order' => 7,
                'depends_on' => null,
            ],

            // EMAIL_MARKETING project type
            [
                'project_type' => 'email_marketing',
                'title' => 'Email Strategy & Sequence Plan',
                'description' => 'Formulate segment definitions, message flows, list rules, and template sizes.',
                'type' => 'research',
                'role_required' => 'marketer',
                'estimated_hours' => 4.00,
                'sla_hours' => 48,
                'sort_order' => 1,
                'depends_on' => null,
            ],
            [
                'project_type' => 'email_marketing',
                'title' => 'Email Template Design',
                'description' => 'Create responsive email layout layouts matching brand identity.',
                'type' => 'design',
                'role_required' => 'designer',
                'estimated_hours' => 6.00,
                'sla_hours' => 72,
                'sort_order' => 2,
                'depends_on' => [1],
            ],
            [
                'project_type' => 'email_marketing',
                'title' => 'Copywriting — Email Sequence',
                'description' => 'Author email sequence copies (subject lines, dynamic tags, body, CTA).',
                'type' => 'content',
                'role_required' => 'marketer',
                'estimated_hours' => 8.00,
                'sla_hours' => 96,
                'sort_order' => 3,
                'depends_on' => [1],
            ],
            [
                'project_type' => 'email_marketing',
                'title' => 'ESP Setup & Integration',
                'description' => 'Configure DNS validation (DKIM, SPF, DMARC) and ESP api bindings.',
                'type' => 'other',
                'role_required' => 'developer',
                'estimated_hours' => 3.00,
                'sla_hours' => 48,
                'sort_order' => 4,
                'depends_on' => [2],
            ],
            [
                'project_type' => 'email_marketing',
                'title' => 'List Segmentation',
                'description' => 'Build automated filters mapping active clients, prospects, and regions.',
                'type' => 'other',
                'role_required' => 'analyst',
                'estimated_hours' => 2.00,
                'sla_hours' => 24,
                'sort_order' => 5,
                'depends_on' => null,
            ],
            [
                'project_type' => 'email_marketing',
                'title' => 'Test Send & QA',
                'description' => 'Check template rendering on dark modes, mobile viewports, and verify links.',
                'type' => 'review',
                'role_required' => 'marketer',
                'estimated_hours' => 1.00,
                'sla_hours' => 24,
                'sort_order' => 6,
                'depends_on' => [3, 4],
            ],
            [
                'project_type' => 'email_marketing',
                'title' => 'Launch & Monitor',
                'description' => 'Trigger live broadcast or release automation and monitor deliveries.',
                'type' => 'other',
                'role_required' => 'marketer',
                'estimated_hours' => 1.00,
                'sla_hours' => 12,
                'sort_order' => 7,
                'depends_on' => [6],
            ],
            [
                'project_type' => 'email_marketing',
                'title' => 'Performance Report',
                'description' => 'Collate delivery rates, bounce percentages, open, and click tracking metrics.',
                'type' => 'report',
                'role_required' => 'analyst',
                'estimated_hours' => 2.00,
                'sla_hours' => 24,
                'sort_order' => 8,
                'depends_on' => [7],
            ],
        ];

        foreach ($templates as $template) {
            DB::table('task_templates')->insert([
                'id' => (string) Str::uuid(),
                'project_type' => $template['project_type'],
                'title' => $template['title'],
                'description' => $template['description'],
                'type' => $template['type'],
                'role_required' => $template['role_required'],
                'estimated_hours' => $template['estimated_hours'],
                'sla_hours' => $template['sla_hours'],
                'sort_order' => $template['sort_order'],
                'depends_on' => $template['depends_on'] ? json_encode($template['depends_on']) : null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
